### ISSUE TITLE
UML Diagramm 

### ISSUE THREAD

**Issue by MazlumY** [hfu-gis/Sigma#5]
Aktivitätsdiagramm erstellen

**Comment by MazlumY** [comment]
[RegistrierungsDiagramm.pdf](https://github.com/hfu-gis/Sigma/files/3771717/RegistrierungsDiagramm.pdf)

[ChatDiagramm.pdf](https://github.com/hfu-gis/Sigma/files/3771718/ChatDiagramm.pdf)

[CharakterErstellenDiagramm.pdf](https://github.com/hfu-gis/Sigma/files/3771719/CharakterErstellenDiagramm.pdf)

[BildergalerieDiagramm.pdf](https://github.com/hfu-gis/Sigma/files/3771723/BildergalerieDiagramm.pdf)

**Comment by phamtomm** [comment]
[Map.pdf](https://github.com/hfu-gis/Sigma/files/3777885/Map.pdf)
[Login.pdf](https://github.com/hfu-gis/Sigma/files/3777886/Login.pdf)
[Support.pdf](https://github.com/hfu-gis/Sigma/files/3777887/Support.pdf)
[Settings.pdf](https://github.com/hfu-gis/Sigma/files/3777888/Settings.pdf)
